curl -X POST http://localhost:8181/api/v1/sessoes/cadastro \
  -H "Content-Type: application/json" \
  -d '{
    "associacao": {
      "nome": "Associação Teste"
    },
    "usuario": {
      "nome_completo": "João da Silva",
      "cpf": "12345678909",
      "email": "joao@email.com",
      "senha": "123456",
      "data_de_nascimento": "1995-10-20",
      "apelido": "joao"
    }
  }'