// GET ALL canteiristas
curl -X GET "http://localhost:8181/api/v1/Canteiristas" \
    -H "Authorization: Bearer 
        eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c3VhcmlvX3V1aWQiOiJlYjNhODJhMS01NmZkLTExZjEtODZlNS05ODI5YTZlM2IxZTEiLCJjYXJnb191dWlkIjoiZWE3ZTNkZmMtNTZmZC0xMWYxLTg2ZTUtOTgyOWE2ZTNiMWUxIiwiYXNzb2NpYWNhb191dWlkIjpudWxsLCJob3J0YV91dWlkIjpudWxsLCJleHAiOjE3Nzk2NjU2MzV9.37t3zAAYC42K9mkWyVgF2sBXgOIRyUoQcNfNBJcfx7c
        " \
    -H "Content-Type: application/json"

###

// GET ALL canteiros
curl -X GET "http://localhost:8181/api/v1/canteiros" \
    -H "Authorization: Bearer 
        eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c3VhcmlvX3V1aWQiOiJlYjNhODJhMS01NmZkLTExZjEtODZlNS05ODI5YTZlM2IxZTEiLCJjYXJnb191dWlkIjoiZWE3ZTNkZmMtNTZmZC0xMWYxLTg2ZTUtOTgyOWE2ZTNiMWUxIiwiYXNzb2NpYWNhb191dWlkIjpudWxsLCJob3J0YV91dWlkIjpudWxsLCJleHAiOjE3Nzk1ODYxMjZ9.lOmyNA0ncveQ9ILMJT5trXdSeaPILn1uvD7Iev5zsgU
        " \
    -H "Content-Type: application/json"

###

// GET filtro de canteiristas (exemplo: buscar por nome)
curl -X GET "http://localhost:8181/api/v1/Canteiristas/filtro?nome_completo=Lucas" \
    -H "Authorization: Bearer 
        eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c3VhcmlvX3V1aWQiOiJlYjNhODJhMS01NmZkLTExZjEtODZlNS05ODI5YTZlM2IxZTEiLCJjYXJnb191dWlkIjoiZWE3ZTNkZmMtNTZmZC0xMWYxLTg2ZTUtOTgyOWE2ZTNiMWUxIiwiYXNzb2NpYWNhb191dWlkIjpudWxsLCJob3J0YV91dWlkIjpudWxsLCJleHAiOjE3Nzk2NjU2MzV9.37t3zAAYC42K9mkWyVgF2sBXgOIRyUoQcNfNBJcfx7c
        " \
    -H "Content-Type: application/json"

###

// GET estatísticas de canteiristas (exemplo: janela de 6 meses)
curl -s -X GET "http://localhost:8181/api/v1/Canteiristas/estatisticas" \
    -H "Authorization: Bearer 
        eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c3VhcmlvX3V1aWQiOiJlYjNhODJhMS01NmZkLTExZjEtODZlNS05ODI5YTZlM2IxZTEiLCJjYXJnb191dWlkIjoiZWE3ZTNkZmMtNTZmZC0xMWYxLTg2ZTUtOTgyOWE2ZTNiMWUxIiwiYXNzb2NpYWNhb191dWlkIjpudWxsLCJob3J0YV91dWlkIjpudWxsLCJleHAiOjE3Nzk2NjU2MzV9.37t3zAAYC42K9mkWyVgF2sBXgOIRyUoQcNfNBJcfx7c
        " \
    -H "Content-Type: application/json"