// GET ALL canteiristas
curl -X GET "http://localhost:8181/api/v1/carteiristas" \
    -H "Authorization: Bearer 
        eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c3VhcmlvX3V1aWQiOiJlYjNhODJhMS01NmZkLTExZjEtODZlNS05ODI5YTZlM2IxZTEiLCJjYXJnb191dWlkIjoiZWE3ZTNkZmMtNTZmZC0xMWYxLTg2ZTUtOTgyOWE2ZTNiMWUxIiwiYXNzb2NpYWNhb191dWlkIjpudWxsLCJob3J0YV91dWlkIjpudWxsLCJleHAiOjE3Nzk1ODYxMjZ9.lOmyNA0ncveQ9ILMJT5trXdSeaPILn1uvD7Iev5zsgU
        " \
    -H "Content-Type: application/json"

###

// GET ALL canteiros
curl -X GET "http://localhost:8181/api/v1/canteiros" \
    -H "Authorization: Bearer 
        eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c3VhcmlvX3V1aWQiOiJlYjNhODJhMS01NmZkLTExZjEtODZlNS05ODI5YTZlM2IxZTEiLCJjYXJnb191dWlkIjoiZWE3ZTNkZmMtNTZmZC0xMWYxLTg2ZTUtOTgyOWE2ZTNiMWUxIiwiYXNzb2NpYWNhb191dWlkIjpudWxsLCJob3J0YV91dWlkIjpudWxsLCJleHAiOjE3Nzk1ODYxMjZ9.lOmyNA0ncveQ9ILMJT5trXdSeaPILn1uvD7Iev5zsgU
        " \
    -H "Content-Type: application/json"