// Atualiza um canteirista
curl -X PUT "http://localhost:8181/api/v1/Canteiristas/4f39c81c-5707-11f1-a047-9829a6e3b1e1" \
  -H "Authorization: Bearer 
    eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c3VhcmlvX3V1aWQiOiJlYjNhODJhMS01NmZkLTExZjEtODZlNS05ODI5YTZlM2IxZTEiLCJjYXJnb191dWlkIjoiZWE3ZTNkZmMtNTZmZC0xMWYxLTg2ZTUtOTgyOWE2ZTNiMWUxIiwiYXNzb2NpYWNhb191dWlkIjpudWxsLCJob3J0YV91dWlkIjpudWxsLCJleHAiOjE3Nzk1OTIwMjF9.yAQ-jVN7C6lLxKY2BRRBImCqxyBy78CH9metxoZyOvk
    " \
  -H "Content-Type: application/json" \
  -d '{
    "nome_completo": "Lucas Canteirista 3 Atualizado",
    "telefone": "(11) 99999-0002",
    "email": "lucas.canteirista3@example.com",
    "apelido": "lucas_atualizado",
    "canteiros": [
      "b901d7e9-56fd-11f1-86e5-9829a6e3b1e1"
    ]
  }'

###